# Configuracion para el acceso a la Base de Datos
spring.jpa.hibernate.ddl-auto=update

# Puerto por donde escucha el servidor cuando se inicie
server.port=5000

# Path de la web API
spring.data.rest.base-path=/api

#Lengua local del proyecto
spring.web.locale=es_ES
spring.web.locale-resolver=fixed

# Datos de conexion con la base de datos MariaDB
spring.datasource.url=jdbc:mariadb://13.222.134.73:3307/gameroster
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=gameroster_user
spring.datasource.password=1234

# Muestra las query SQL que ejecuta Hibernate
spring.jpa.show-sql=true

# Habilitar Flyway
spring.flyway.enabled=true
# Ejecutar flyway.repair() automaticamente antes de migrar (opcional)
spring.flyway.repair-on-migrate=true
# Ubicacion de los scripts de migracion
spring.flyway.locations=classpath:db/migration

jwt.secret=ZmFrZWtleWZha2VrZXlmYWtla2V5ZmFrZWtleWZha2VrZXk=
jwt.expiration=86400

springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.default-models-expand-depth=-1

